* Decorators
  :PROPERTIES:
  :CUSTOM_ID: decorators
  :END:

** Functions in Python are first-class
   :PROPERTIES:
   :CUSTOM_ID: functions-in-python-are-first-class
   :END:

Unlike other languages, python treats functions as first-class citizens.
That means that the language treats functions and data in the same way.
Like data, functions can be assigned to variables, copied, and used as
return values. They can also be passed into other functions as
parametets.

#+BEGIN_SRC python
    def foo():
        print('foo!')

    def bar(function):
        function()

    bar(foo)
    # prints 'foo!'
#+END_SRC

** Decorators wrap existing functions
   :PROPERTIES:
   :CUSTOM_ID: decorators-wrap-existing-functions
   :END:

A decorator is a callable that takes a callable as an argument and
returns another callable to replace it.

*** The @ syntax
    :PROPERTIES:
    :CUSTOM_ID: the-syntax
    :END:

The =@= syntax, is used to specify that the function =bar= should be
wrapped or /decorated/ by *foo*. The following statement is exactly
equivalent to using =@=.

#+BEGIN_SRC python
    def foo(fn):
        def inner():
            print('About to call function.')
            fn()
            print('Finished calling function.')
        return inner

    @foo
    def bar():
        print('Calling function bar.')
#+END_SRC

#+BEGIN_SRC python

    bar = foo(bar)
#+END_SRC
